"""
Rebuild MNR ontology with Owlready2.

Important:
- This script DOES NOT read or load the original MNR_Ontology.owl file.
- It recreates the same ontology logic by defining classes, properties,
  subclass relations, restrictions, equivalent classes, and disjoint groups.
- Output file: MNR_Ontology_rebuilt.owl
"""

from owlready2 import *
import types


ONTOLOGY_IRI = "http://www.semanticweb.org/sunny/ontologies/2026/3/untitled-ontology-4"
OUTPUT_FILE = "MNR_Ontology_rebuilt.owl"


CLASS_NAMES = ['ATC',
 'Amtrak',
 'Assault',
 'Bridge_Strike',
 'Bridges',
 'CP12',
 'CP216',
 'CP274',
 'CP75',
 'CTC_System',
 'Capital',
 'Car_Cleaning',
 'Carbody',
 'Catenary_System',
 'Catenary_System_-_No_Defect_Found',
 'Checked_Equipment_No_Defect_Found',
 'Collision_-_Train_Accident',
 'Communication',
 'Communication_Systems',
 'Con_Edison',
 'Conductors',
 'Consist',
 'Contractor_Injury',
 'Crew_Dispatching',
 'Crew_Performance',
 'Crew_Reported_Symptom_-_NDF',
 'Customer-Related',
 'Customer_Service',
 'Department',
 'Derailment',
 'Doors',
 'Employe_Injury',
 'Employee_Illness',
 'Employee_Injury',
 'Engineering',
 'Engineers',
 'Environmental',
 'Extreme_Cold',
 'Extreme_Heat',
 'Fare_Dispute',
 'Fatality',
 'Fixed_Bridge',
 'Fleet_Management',
 'Freight_Railroad',
 'Fuel',
 'Fuel_Supply',
 'Gapped',
 'Grade_Crossing',
 'Grade_Crossing_Incident',
 'Grade_Crossings',
 'Grand_Central_Terminal',
 'Grand_Central_Terminal_Complex',
 'Group_Move',
 'HVAC',
 'Head_End_Power',
 'Hold',
 'Human_Obstruction_On_or_Near_Platform',
 'Human_or_Animal_Interference',
 'Hurricane',
 'Illness',
 'Infrastructure_Incident',
 'Injury',
 'Inspected_-_No_Defect_Found',
 'Insulated_Joint',
 'Interlocking',
 'Interlocking_-_Track_Circuit',
 'Intermediate_Territory',
 'Intermediate_Territory_-_Track_Circuit',
 'Lighting',
 'Lightning_Strike',
 'Local_Utility',
 'Local_Utility_Outage',
 'MNR_Delay_Category',
 'Main_Diesel_Engine',
 'Mask_Compliance',
 'Mechanical',
 'Movable_Bridge',
 'Movable_Bridge_-_No_Cause_Found',
 'Moveable_Bridge',
 'NYC_Water',
 'No_Cause_Found',
 'Non-Railroad_Incident',
 'Object_Left_On_Train',
 'On_Board_Trains',
 'Operating_Restrictions',
 'Other',
 'Other_Agency',
 'Out_of_Slot',
 'Outlying_Stations',
 'PTC',
 'PTC_System',
 'Police',
 'Power',
 'Power_Collection',
 'Public_Safety_Protocols',
 'ROW_-_NDF',
 'ROW_Conditions',
 'Refused_Medical_Attention',
 'Right-of-Way',
 'SCADA',
 'Security',
 'Shortage_of_Crewmen',
 'Signal',
 'Signal_Power_System',
 'Signals',
 'Slip_Slide',
 'Special_Event_Ridership',
 'Stations',
 'Storms_To_Be_Named',
 'Structures',
 'Substation',
 'Switch',
 'Switch_Failure',
 'Symptom',
 'System',
 'Third_Rail_System',
 'To_Be_Determined',
 'Track_Circuit_-_Bond',
 'Track_Equipment_Failure',
 'Track_and_Right-of-Way',
 'Train_Dispatching',
 'Train_Error',
 'Train_Routing',
 'Transportation',
 'Trespasser',
 'Tropical_Storm',
 'Unclassified',
 'Unfounded_Non_MNR_Report',
 'Unruly_Passenger',
 'Unscheduled_Turn_Of_Equipment',
 'Vandalism',
 'Wild_Detector',
 'Wind',
 'Winter_Storm',
 'Yard_Operations',
 'Yard_master',
 'switching_crew',
 "'Speed_Restriction",
 'Brake_&_Air_Supply',
 'CS/ATC',
 'Cab_Signal_ATC/PTC',
 'Cab_Signal_ATC/PTC_NDF',
 'Catenary/Power',
 'Change_in_Track_/_Platform',
 'Coast_Guard/Movable_Bridge_Openings',
 'Coast_Guard/Moveable_Bridge_Openings',
 'Communications_&_SIgnals',
 'Controls_&_Diagnostics',
 'Crossing_Check/No_Defect_Found',
 'Crossing_Check_/_No_Defect_Found',
 'Debris_/_Vandalism',
 'ECT_(Engineer/Conductor/Trainmen)',
 'Employee_Injury/Symptom',
 'Environmental_Obstruction_/_Wildlife',
 'FRA/NTSB/PTSB/Other_Agency',
 'Fire_On/Near_Tracks',
 'Gapped/Symptom',
 'Heavy_Ridership_/_Slow_Loading',
 'Lavatories_&_Toilets',
 'Main_&_Aux_Electric_Power',
 'Non-Railroad_/_I&C',
 'Oil_Leak/Spill',
 'Program_&_Production_Trackwork',
 'Propulsion_&_Dynamic_Brake',
 'Rails/Track',
 'Rain/Flooding',
 'Shops,_Yards,_Facilities',
 'Speed_Restriction_(weather-related)',
 'Sperry;_Cyclical_track_inspection/testing',
 'Telco/Utilities',
 'Track_&_Structures',
 'Trucks_&_Suspension',
 'Unscheduled_Turn_Of_Equipment/Symptom']

SUBCLASS_RELATIONS = [('ATC', 'Symptom'),
 ('Amtrak', 'System'),
 ('Assault', 'Symptom'),
 ('Bridge_Strike', 'System'),
 ('Bridges', 'System'),
 ('CP12', 'System'),
 ('CP216', 'System'),
 ('CP274', 'System'),
 ('CP75', 'System'),
 ('CTC_System', 'Symptom'),
 ('Capital', 'Department'),
 ('Car_Cleaning', 'System'),
 ('Carbody', 'System'),
 ('Catenary_System', 'Symptom'),
 ('Catenary_System_-_No_Defect_Found', 'Symptom'),
 ('Checked_Equipment_No_Defect_Found', 'System'),
 ('Collision_-_Train_Accident', 'System'),
 ('Communication', 'System'),
 ('Communication_Systems', 'Symptom'),
 ('Con_Edison', 'System'),
 ('Conductors', 'Symptom'),
 ('Consist', 'System'),
 ('Contractor_Injury', 'System'),
 ('Crew_Dispatching', 'System'),
 ('Crew_Performance', 'System'),
 ('Crew_Reported_Symptom_-_NDF', 'Symptom'),
 ('Customer-Related', 'Department'),
 ('Customer_Service', 'System'),
 ('Department', 'MNR_Delay_Category'),
 ('Derailment', 'System'),
 ('Doors', 'System'),
 ('Employe_Injury', 'System'),
 ('Employee_Illness', 'System'),
 ('Employee_Injury', 'System'),
 ('Engineering', 'Department'),
 ('Engineers', 'Symptom'),
 ('Environmental', 'Department'),
 ('Extreme_Cold', 'System'),
 ('Extreme_Heat', 'System'),
 ('Fare_Dispute', 'System'),
 ('Fatality', 'System'),
 ('Fixed_Bridge', 'Symptom'),
 ('Fleet_Management', 'System'),
 ('Freight_Railroad', 'System'),
 ('Fuel', 'Symptom'),
 ('Fuel_Supply', 'System'),
 ('Gapped', 'System'),
 ('Grade_Crossing', 'System'),
 ('Grade_Crossing_Incident', 'System'),
 ('Grade_Crossings', 'Symptom'),
 ('Grand_Central_Terminal', 'System'),
 ('Grand_Central_Terminal_Complex', 'System'),
 ('Group_Move', 'System'),
 ('HVAC', 'System'),
 ('Head_End_Power', 'System'),
 ('Hold', 'Department'),
 ('Human_Obstruction_On_or_Near_Platform', 'System'),
 ('Human_or_Animal_Interference', 'Symptom'),
 ('Hurricane', 'System'),
 ('Illness', 'System'),
 ('Infrastructure_Incident', 'System'),
 ('Injury', 'System'),
 ('Inspected_-_No_Defect_Found', 'Symptom'),
 ('Insulated_Joint', 'Symptom'),
 ('Interlocking', 'Symptom'),
 ('Interlocking_-_Track_Circuit', 'Symptom'),
 ('Intermediate_Territory', 'Symptom'),
 ('Intermediate_Territory_-_Track_Circuit', 'Symptom'),
 ('Lighting', 'System'),
 ('Lightning_Strike', 'System'),
 ('Local_Utility', 'Symptom'),
 ('Local_Utility_Outage', 'System'),
 ('Main_Diesel_Engine', 'System'),
 ('Mask_Compliance', 'System'),
 ('Mechanical', 'Department'),
 ('Movable_Bridge', 'Symptom'),
 ('Movable_Bridge_-_No_Cause_Found', 'Symptom'),
 ('Moveable_Bridge', 'Symptom'),
 ('NYC_Water', 'System'),
 ('No_Cause_Found', 'Symptom'),
 ('Non-Railroad_Incident', 'System'),
 ('Object_Left_On_Train', 'System'),
 ('On_Board_Trains', 'System'),
 ('Operating_Restrictions', 'Symptom'),
 ('Other', 'Department'),
 ('Other_Agency', 'Department'),
 ('Out_of_Slot', 'System'),
 ('Outlying_Stations', 'System'),
 ('PTC', 'Symptom'),
 ('PTC_System', 'Symptom'),
 ('Police', 'Department'),
 ('Power', 'System'),
 ('Power_Collection', 'System'),
 ('Public_Safety_Protocols', 'Symptom'),
 ('ROW_-_NDF', 'Symptom'),
 ('ROW_Conditions', 'Symptom'),
 ('Refused_Medical_Attention', 'System'),
 ('Right-of-Way', 'System'),
 ('SCADA', 'Symptom'),
 ('Security', 'System'),
 ('Shortage_of_Crewmen', 'Symptom'),
 ('Signal', 'System'),
 ('Signal_Power_System', 'Symptom'),
 ('Signals', 'Symptom'),
 ('Slip_Slide', 'System'),
 ('Special_Event_Ridership', 'System'),
 ('Stations', 'System'),
 ('Storms_To_Be_Named', 'Symptom'),
 ('Structures', 'Symptom'),
 ('Substation', 'Symptom'),
 ('Switch', 'Symptom'),
 ('Switch_Failure', 'Symptom'),
 ('Symptom', 'MNR_Delay_Category'),
 ('System', 'MNR_Delay_Category'),
 ('Third_Rail_System', 'Symptom'),
 ('To_Be_Determined', 'Symptom'),
 ('Track_Circuit_-_Bond', 'Symptom'),
 ('Track_Equipment_Failure', 'Symptom'),
 ('Track_and_Right-of-Way', 'System'),
 ('Train_Dispatching', 'System'),
 ('Train_Error', 'System'),
 ('Train_Routing', 'System'),
 ('Transportation', 'Department'),
 ('Trespasser', 'System'),
 ('Tropical_Storm', 'System'),
 ('Unclassified', 'System'),
 ('Unfounded_Non_MNR_Report', 'System'),
 ('Unruly_Passenger', 'Symptom'),
 ('Unscheduled_Turn_Of_Equipment', 'System'),
 ('Vandalism', 'System'),
 ('Wild_Detector', 'System'),
 ('Wind', 'System'),
 ('Winter_Storm', 'System'),
 ('Yard_Operations', 'System'),
 ('Yard_master', 'Symptom'),
 ('switching_crew', 'Symptom'),
 ("'Speed_Restriction", 'Symptom'),
 ('Brake_&_Air_Supply', 'System'),
 ('CS/ATC', 'Symptom'),
 ('Cab_Signal_ATC/PTC', 'System'),
 ('Cab_Signal_ATC/PTC_NDF', 'Symptom'),
 ('Catenary/Power', 'System'),
 ('Change_in_Track_/_Platform', 'System'),
 ('Coast_Guard/Movable_Bridge_Openings', 'System'),
 ('Coast_Guard/Moveable_Bridge_Openings', 'System'),
 ('Communications_&_SIgnals', 'System'),
 ('Controls_&_Diagnostics', 'System'),
 ('Crossing_Check/No_Defect_Found', 'Symptom'),
 ('Crossing_Check_/_No_Defect_Found', 'System'),
 ('Debris_/_Vandalism', 'System'),
 ('ECT_(Engineer/Conductor/Trainmen)', 'Symptom'),
 ('Employee_Injury/Symptom', 'Symptom'),
 ('Environmental_Obstruction_/_Wildlife', 'System'),
 ('FRA/NTSB/PTSB/Other_Agency', 'System'),
 ('Fire_On/Near_Tracks', 'System'),
 ('Gapped/Symptom', 'Symptom'),
 ('Heavy_Ridership_/_Slow_Loading', 'System'),
 ('Lavatories_&_Toilets', 'System'),
 ('Main_&_Aux_Electric_Power', 'System'),
 ('Non-Railroad_/_I&C', 'System'),
 ('Oil_Leak/Spill', 'System'),
 ('Program_&_Production_Trackwork', 'Symptom'),
 ('Propulsion_&_Dynamic_Brake', 'System'),
 ('Rails/Track', 'Symptom'),
 ('Rain/Flooding', 'System'),
 ('Shops,_Yards,_Facilities', 'System'),
 ('Speed_Restriction_(weather-related)', 'System'),
 ('Sperry;_Cyclical_track_inspection/testing', 'Symptom'),
 ('Telco/Utilities', 'Symptom'),
 ('Track_&_Structures', 'System'),
 ('Trucks_&_Suspension', 'System'),
 ('Unscheduled_Turn_Of_Equipment/Symptom', 'Symptom')]

OBJECT_PROPERTIES = [('has_Symptom', ['System'], ['Symptom']), ('has_System', ['Department'], ['System'])]

DATA_PROPERTIES = [('is_Disabled', [], ['boolean'])]

SUBCLASS_RESTRICTIONS = [('Capital', 'has_Symptom', ['To_Be_Determined']),
 ('Capital',
  'has_System',
  ['Bridges',
   'Contractor_Injury',
   'Grand_Central_Terminal_Complex',
   'Signal',
   'Stations',
   'Track_and_Right-of-Way',
   'Unclassified',
   'Catenary/Power',
   'Non-Railroad_/_I&C',
   'Shops,_Yards,_Facilities']),
 ('Crew_Dispatching', 'has_Symptom', ['Shortage_of_Crewmen']),
 ('Crew_Performance',
  'has_Symptom',
  ['Conductors', 'Crew_Reported_Symptom_-_NDF', 'Engineers', 'ECT_(Engineer/Conductor/Trainmen)', 'Gapped/Symptom']),
 ('Customer-Related', 'has_Symptom', ['To_Be_Determined']),
 ('Customer-Related',
  'has_System',
  ['Customer_Service',
   'Fare_Dispute',
   'Group_Move',
   'Illness',
   'Injury',
   'Refused_Medical_Attention',
   'Special_Event_Ridership',
   'Unclassified',
   'Change_in_Track_/_Platform',
   'Heavy_Ridership_/_Slow_Loading']),
 ('Engineering', 'has_System', ['Power', 'Unclassified', 'Communications_&_SIgnals', 'Track_&_Structures']),
 ('Extreme_Cold', 'has_Symptom', ["'Speed_Restriction"]),
 ('Extreme_Heat', 'has_Symptom', ["'Speed_Restriction"]),
 ('Fleet_Management', 'has_Symptom', ['Fuel', 'Unscheduled_Turn_Of_Equipment']),
 ('Hold', 'has_Symptom', ['To_Be_Determined']),
 ('Hold', 'has_System', ['CP12', 'CP216', 'CP274', 'CP75', 'Out_of_Slot', 'Unclassified']),
 ('Hurricane', 'has_Symptom', ['Storms_To_Be_Named']),
 ('Mechanical',
  'has_System',
  ['Car_Cleaning',
   'Carbody',
   'Checked_Equipment_No_Defect_Found',
   'Communication',
   'Consist',
   'Derailment',
   'Doors',
   'Employee_Injury',
   'Fuel_Supply',
   'HVAC',
   'Head_End_Power',
   'Lighting',
   'Main_Diesel_Engine',
   'Power_Collection',
   'Unclassified',
   'Unscheduled_Turn_Of_Equipment',
   'Brake_&_Air_Supply',
   'Cab_Signal_ATC/PTC',
   'Controls_&_Diagnostics',
   'Lavatories_&_Toilets',
   'Main_&_Aux_Electric_Power',
   'Propulsion_&_Dynamic_Brake',
   'Trucks_&_Suspension']),
 ('On_Board_Trains', 'has_Symptom', ['Assault', 'Public_Safety_Protocols', 'Unruly_Passenger']),
 ('Other', 'has_Symptom', ['To_Be_Determined']),
 ('Other',
  'has_System',
  ['Amtrak',
   'Bridge_Strike',
   'Checked_Equipment_No_Defect_Found',
   'Collision_-_Train_Accident',
   'Derailment',
   'Employee_Injury',
   'Human_Obstruction_On_or_Near_Platform',
   'Infrastructure_Incident',
   'Unclassified',
   'Unfounded_Non_MNR_Report',
   'Wild_Detector',
   'Coast_Guard/Moveable_Bridge_Openings',
   'Crossing_Check_/_No_Defect_Found',
   'Debris_/_Vandalism']),
 ('Other_Agency',
  'has_System',
  ['Amtrak',
   'Bridge_Strike',
   'Con_Edison',
   'Derailment',
   'Freight_Railroad',
   'Grade_Crossing_Incident',
   'Local_Utility_Outage',
   'NYC_Water',
   'Unclassified',
   'Coast_Guard/Movable_Bridge_Openings',
   'FRA/NTSB/PTSB/Other_Agency',
   'Fire_On/Near_Tracks']),
 ('Police',
  'has_System',
  ['Employe_Injury',
   'Fare_Dispute',
   'Fatality',
   'Grade_Crossing',
   'Grand_Central_Terminal',
   'Mask_Compliance',
   'Non-Railroad_Incident',
   'Object_Left_On_Train',
   'On_Board_Trains',
   'Outlying_Stations',
   'Right-of-Way',
   'Security',
   'Trespasser',
   'Unclassified',
   'Vandalism']),
 ('Power',
  'has_Symptom',
  ['Catenary_System',
   'Catenary_System_-_No_Defect_Found',
   'Employee_Injury',
   'Human_or_Animal_Interference',
   'Local_Utility',
   'Moveable_Bridge',
   'SCADA',
   'Signal_Power_System',
   'Substation',
   'Third_Rail_System',
   'To_Be_Determined',
   'Track_Circuit_-_Bond']),
 ('Transportation',
  'has_System',
  ['Crew_Dispatching',
   'Crew_Performance',
   'Employee_Illness',
   'Employee_Injury',
   'Fleet_Management',
   'Gapped',
   'Train_Dispatching',
   'Train_Error',
   'Train_Routing',
   'Unclassified',
   'Yard_Operations']),
 ('Tropical_Storm', 'has_Symptom', ['Storms_To_Be_Named']),
 ('Unclassified', 'has_Symptom', ['To_Be_Determined']),
 ('Wild_Detector', 'has_Symptom', ['Inspected_-_No_Defect_Found']),
 ('Winter_Storm', 'has_Symptom', ['Storms_To_Be_Named']),
 ('Yard_Operations', 'has_Symptom', ['Yard_master', 'switching_crew']),
 ('Cab_Signal_ATC/PTC', 'has_Symptom', ['ATC', 'PTC', 'Cab_Signal_ATC/PTC_NDF']),
 ('Communications_&_SIgnals',
  'has_Symptom',
  ['CTC_System',
   'Communication_Systems',
   'Employee_Injury',
   'Grade_Crossings',
   'Interlocking',
   'Interlocking_-_Track_Circuit',
   'Intermediate_Territory',
   'Intermediate_Territory_-_Track_Circuit',
   'Moveable_Bridge',
   'No_Cause_Found',
   'PTC_System',
   'Signals',
   'Switch_Failure',
   'To_Be_Determined',
   'CS/ATC',
   'Crossing_Check/No_Defect_Found',
   'Telco/Utilities']),
 ('Rain/Flooding', 'has_Symptom', ['Storms_To_Be_Named']),
 ('Track_&_Structures',
  'has_Symptom',
  ['Fixed_Bridge',
   'Insulated_Joint',
   'Movable_Bridge',
   'Movable_Bridge_-_No_Cause_Found',
   'Operating_Restrictions',
   'ROW_-_NDF',
   'ROW_Conditions',
   'Structures',
   'Switch',
   'To_Be_Determined',
   'Track_Equipment_Failure',
   'Employee_Injury/Symptom',
   'Program_&_Production_Trackwork',
   'Rails/Track',
   'Sperry;_Cyclical_track_inspection/testing'])]

EQUIVALENT_CLASS_RESTRICTIONS = [('Environmental',
  'has_System',
  ['Extreme_Cold',
   'Extreme_Heat',
   'Hurricane',
   'Lightning_Strike',
   'Slip_Slide',
   'Tropical_Storm',
   'Unclassified',
   'Wind',
   'Winter_Storm',
   'Environmental_Obstruction_/_Wildlife',
   'Oil_Leak/Spill',
   'Rain/Flooding',
   'Speed_Restriction_(weather-related)'])]

DISJOINT_CLASS_GROUPS = [['ATC',
  'Assault',
  'CTC_System',
  'Catenary_System',
  'Catenary_System_-_No_Defect_Found',
  'Communication_Systems',
  'Conductors',
  'Crew_Reported_Symptom_-_NDF',
  'Engineers',
  'Fixed_Bridge',
  'Fuel',
  'Grade_Crossings',
  'Human_or_Animal_Interference',
  'Inspected_-_No_Defect_Found',
  'Insulated_Joint',
  'Interlocking',
  'Interlocking_-_Track_Circuit',
  'Intermediate_Territory',
  'Intermediate_Territory_-_Track_Circuit',
  'Local_Utility',
  'Movable_Bridge',
  'Movable_Bridge_-_No_Cause_Found',
  'Moveable_Bridge',
  'No_Cause_Found',
  'Operating_Restrictions',
  'PTC',
  'PTC_System',
  'Public_Safety_Protocols',
  'ROW_-_NDF',
  'ROW_Conditions',
  'SCADA',
  'Shortage_of_Crewmen',
  'Signal_Power_System',
  'Signals',
  'Storms_To_Be_Named',
  'Structures',
  'Substation',
  'Switch',
  'Switch_Failure',
  'Third_Rail_System',
  'To_Be_Determined',
  'Track_Circuit_-_Bond',
  'Track_Equipment_Failure',
  'Unruly_Passenger',
  'Yard_master',
  'switching_crew',
  "'Speed_Restriction",
  'CS/ATC',
  'Cab_Signal_ATC/PTC_NDF',
  'Crossing_Check/No_Defect_Found',
  'ECT_(Engineer/Conductor/Trainmen)',
  'Employee_Injury/Symptom',
  'Gapped/Symptom',
  'Program_&_Production_Trackwork',
  'Rails/Track',
  'Sperry;_Cyclical_track_inspection/testing',
  'Telco/Utilities',
  'Unscheduled_Turn_Of_Equipment/Symptom'],
 ['Amtrak',
  'Bridge_Strike',
  'Bridges',
  'CP12',
  'CP216',
  'CP274',
  'CP75',
  'Car_Cleaning',
  'Carbody',
  'Checked_Equipment_No_Defect_Found',
  'Collision_-_Train_Accident',
  'Communication',
  'Con_Edison',
  'Consist',
  'Contractor_Injury',
  'Crew_Dispatching',
  'Crew_Performance',
  'Customer_Service',
  'Derailment',
  'Doors',
  'Employe_Injury',
  'Employee_Illness',
  'Employee_Injury',
  'Extreme_Cold',
  'Extreme_Heat',
  'Fare_Dispute',
  'Fatality',
  'Fleet_Management',
  'Freight_Railroad',
  'Fuel_Supply',
  'Gapped',
  'Grade_Crossing',
  'Grade_Crossing_Incident',
  'Grand_Central_Terminal',
  'Grand_Central_Terminal_Complex',
  'Group_Move',
  'HVAC',
  'Head_End_Power',
  'Human_Obstruction_On_or_Near_Platform',
  'Hurricane',
  'Illness',
  'Infrastructure_Incident',
  'Injury',
  'Lighting',
  'Lightning_Strike',
  'Local_Utility_Outage',
  'Main_Diesel_Engine',
  'Mask_Compliance',
  'NYC_Water',
  'Non-Railroad_Incident',
  'Object_Left_On_Train',
  'On_Board_Trains',
  'Out_of_Slot',
  'Outlying_Stations',
  'Power',
  'Power_Collection',
  'Refused_Medical_Attention',
  'Right-of-Way',
  'Security',
  'Signal',
  'Slip_Slide',
  'Special_Event_Ridership',
  'Stations',
  'Track_and_Right-of-Way',
  'Train_Dispatching',
  'Train_Error',
  'Train_Routing',
  'Trespasser',
  'Tropical_Storm',
  'Unclassified',
  'Unfounded_Non_MNR_Report',
  'Unscheduled_Turn_Of_Equipment',
  'Vandalism',
  'Wild_Detector',
  'Wind',
  'Winter_Storm',
  'Yard_Operations',
  'Brake_&_Air_Supply',
  'Cab_Signal_ATC/PTC',
  'Catenary/Power',
  'Change_in_Track_/_Platform',
  'Coast_Guard/Movable_Bridge_Openings',
  'Coast_Guard/Moveable_Bridge_Openings',
  'Communications_&_SIgnals',
  'Controls_&_Diagnostics',
  'Crossing_Check_/_No_Defect_Found',
  'Debris_/_Vandalism',
  'Environmental_Obstruction_/_Wildlife',
  'FRA/NTSB/PTSB/Other_Agency',
  'Fire_On/Near_Tracks',
  'Heavy_Ridership_/_Slow_Loading',
  'Lavatories_&_Toilets',
  'Main_&_Aux_Electric_Power',
  'Non-Railroad_/_I&C',
  'Oil_Leak/Spill',
  'Propulsion_&_Dynamic_Brake',
  'Rain/Flooding',
  'Shops,_Yards,_Facilities',
  'Speed_Restriction_(weather-related)',
  'Track_&_Structures',
  'Trucks_&_Suspension'],
 ['Amtrak',
  'Bridge_Strike',
  'CP12',
  'CP216',
  'CP274',
  'CP75',
  'Car_Cleaning',
  'Carbody',
  'Checked_Equipment_No_Defect_Found',
  'Collision_-_Train_Accident',
  'Communication',
  'Con_Edison',
  'Consist',
  'Crew_Dispatching',
  'Crew_Performance',
  'Customer_Service',
  'Derailment',
  'Doors',
  'Employe_Injury',
  'Employee_Illness',
  'Employee_Injury',
  'Extreme_Cold',
  'Extreme_Heat',
  'Fare_Dispute',
  'Fatality',
  'Fleet_Management',
  'Freight_Railroad',
  'Fuel_Supply',
  'Gapped',
  'Grade_Crossing',
  'Grade_Crossing_Incident',
  'Grand_Central_Terminal',
  'Group_Move',
  'HVAC',
  'Head_End_Power',
  'Human_Obstruction_On_or_Near_Platform',
  'Hurricane',
  'Illness',
  'Infrastructure_Incident',
  'Injury',
  'Lighting',
  'Lightning_Strike',
  'Local_Utility_Outage',
  'Main_Diesel_Engine',
  'Mask_Compliance',
  'NYC_Water',
  'Non-Railroad_Incident',
  'Object_Left_On_Train',
  'On_Board_Trains',
  'Out_of_Slot',
  'Outlying_Stations',
  'Power',
  'Power_Collection',
  'Refused_Medical_Attention',
  'Right-of-Way',
  'Security',
  'Slip_Slide',
  'Special_Event_Ridership',
  'Train_Dispatching',
  'Train_Error',
  'Train_Routing',
  'Trespasser',
  'Tropical_Storm',
  'Unclassified',
  'Unfounded_Non_MNR_Report',
  'Unscheduled_Turn_Of_Equipment',
  'Vandalism',
  'Wild_Detector',
  'Wind',
  'Winter_Storm',
  'Yard_Operations',
  'Brake_&_Air_Supply',
  'Cab_Signal_ATC/PTC',
  'Change_in_Track_/_Platform',
  'Coast_Guard/Movable_Bridge_Openings',
  'Coast_Guard/Moveable_Bridge_Openings',
  'Communications_&_SIgnals',
  'Controls_&_Diagnostics',
  'Crossing_Check_/_No_Defect_Found',
  'Debris_/_Vandalism',
  'Environmental_Obstruction_/_Wildlife',
  'FRA/NTSB/PTSB/Other_Agency',
  'Fire_On/Near_Tracks',
  'Heavy_Ridership_/_Slow_Loading',
  'Lavatories_&_Toilets',
  'Main_&_Aux_Electric_Power',
  'Oil_Leak/Spill',
  'Propulsion_&_Dynamic_Brake',
  'Rain/Flooding',
  'Speed_Restriction_(weather-related)',
  'Track_&_Structures',
  'Trucks_&_Suspension'],
 ['Capital',
  'Customer-Related',
  'Engineering',
  'Environmental',
  'Hold',
  'Mechanical',
  'Other',
  'Other_Agency',
  'Police',
  'Transportation']]


def make_ontology():
    """
    Build the MNR ontology directly with Owlready2.
    This function does not call .load() on the original OWL file.
    """
    onto = get_ontology(ONTOLOGY_IRI)

    with onto:
        class_map = {}

        # 1. Create all named classes first.
        # Some OWL class names contain '/', '&', '-', commas, etc.,
        # so we use types.new_class instead of normal Python class syntax.
        for class_name in CLASS_NAMES:
            if class_name not in class_map:
                class_map[class_name] = types.new_class(class_name, (Thing,))

        # 2. Create object properties.
        property_map = {}
        for property_name, domain_names, range_names in OBJECT_PROPERTIES:
            property_class = types.new_class(property_name, (ObjectProperty,))
            property_map[property_name] = property_class

            property_class.domain = [class_map[name] for name in domain_names if name in class_map]
            property_class.range = [class_map[name] for name in range_names if name in class_map]

        # 3. Create data properties.
        datatype_map = {
            "boolean": bool,
            "string": str,
            "integer": int,
            "decimal": float,
            "float": float,
            "double": float,
        }

        for property_name, domain_names, range_names in DATA_PROPERTIES:
            property_class = types.new_class(property_name, (DataProperty,))
            property_map[property_name] = property_class

            property_class.domain = [class_map[name] for name in domain_names if name in class_map]
            property_class.range = [
                datatype_map[name] for name in range_names if name in datatype_map
            ]

        # 4. Add normal subclass relations.
        for child_name, parent_name in SUBCLASS_RELATIONS:
            child_class = class_map[child_name]
            parent_class = class_map[parent_name]

            # Remove default Thing parent when a more specific parent exists.
            if Thing in child_class.is_a:
                child_class.is_a.remove(Thing)

            if parent_class not in child_class.is_a:
                child_class.is_a.append(parent_class)

        # Helper: build either a single class expression or a union expression.
        def build_class_expression(value_names):
            value_classes = [class_map[name] for name in value_names if name in class_map]

            if not value_classes:
                return None

            if len(value_classes) == 1:
                return value_classes[0]

            return Or(value_classes)

        # 5. Add subclass restrictions.
        # Example:
        # Capital subclassOf has_System some (Bridges or Signal or ...)
        for class_name, property_name, value_names in SUBCLASS_RESTRICTIONS:
            class_obj = class_map[class_name]
            property_obj = property_map[property_name]
            value_expression = build_class_expression(value_names)

            if value_expression is not None:
                class_obj.is_a.append(property_obj.some(value_expression))

        # 6. Add equivalent class restrictions.
        # Example:
        # Environmental equivalentTo has_System some (...)
        for class_name, property_name, value_names in EQUIVALENT_CLASS_RESTRICTIONS:
            class_obj = class_map[class_name]
            property_obj = property_map[property_name]
            value_expression = build_class_expression(value_names)

            if value_expression is not None:
                class_obj.equivalent_to.append(property_obj.some(value_expression))

        # 7. Add disjoint class groups.
        for group in DISJOINT_CLASS_GROUPS:
            group_classes = [class_map[name] for name in group if name in class_map]

            if len(group_classes) >= 2:
                AllDisjoint(group_classes)

    return onto, class_map, property_map


if __name__ == "__main__":
    ontology, classes, properties = make_ontology()

    ontology.save(file=OUTPUT_FILE, format="rdfxml")

    print("Ontology rebuilt successfully.")
    print(f"Classes: {len(classes)}")
    print(f"Properties: {len(properties)}")
    print(f"Saved to: {OUTPUT_FILE}")
